version: '3.7'
services:
app-prod:
    container_name: dockerized-react-app
    build:
      context: .
      dockerfile: Dockerfile-PROD
    ports:
      - '8080:80'
# Ative o container
# docker-compose -f docker-compose-prod.yml up -d --build
# o parâmetro -f serve para especificar o arquivo a ser usado pelo docker-compose.

# Desative o container
# docker-compose stop