# build environment
FROM node:13-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install — silent
RUN npm install react-scripts@3.0.1 -g — silent
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html

# React Router and Nginx
# Se o projeto estiver usando o React Router, 
# será necessário alterar a configuração padrão do Nginx 
# em tempo de execução durante a construção da Imagem, 
# adicionando estas linhas:
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]